seed: 42
save_path: "model_s=4.pt"

# Architecture
hidden_size: 2

#Optimizer
learning_rate: 0.001
weight_decay: 0.01
# LR scheduler
step_size: 50
gamma: 0.5
# History
epochs: 100
batch_size: 32

# Data
train_size: 320 #maximum is 400, the rest is used for testing
frac_val: 0.1 # % of train data to use for validation
